apiVersion: apps/v1
kind: Deployment
metadata:
  name: shoppingapi-deployment
  labels:
    app: shoppingapi
spec:
  replicas: 2
  selector:
    matchLabels:
      app: shoppingapi
  template:
    metadata:
      labels:
        app: shoppingapi
    spec:
      containers:
      - name: shoppingapi
        image: warshoppingacr.azurecr.io/shoppingapi:v1
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 80
        env:
          - name: ASPNETCORE_ENVIRONMENT
            value: Development
          - name: DatabaseSettings__ConnectionString
            valueFrom:
              configMapKeyRef:
                name: mongo-configmap
                key: connection_string
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "300m"
      imagePullSecrets:
        - name: acr-secret

---
kind: Service
apiVersion: v1
metadata:
  name:  shoppingapi-service
spec:
  selector:
    app:  shoppingapi
  ports:
  - protocol: TCP
    port: 80