apiVersion: apps/v1
kind: Deployment
metadata:
  name: shoppingclient-deployment
  labels:
    app: shoppingclient
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shoppingclient
  template:
    metadata:
      labels:
        app: shoppingclient
    spec:
      containers:
      - name: shoppingclient
        image: wagnerapramos/shoppingclient:latest
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 80
        env:
          - name: ASPNETCORE_ENVIRONMENT
            value: Development
          - name: ConnectionStrings__ShoppingApiUrl
            valueFrom:
              configMapKeyRef:
                name: shoppingclient-configmap
                key: shoppingapi_url
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
---
kind: Service
apiVersion: v1
metadata:
  name:  shoppingclient-service
spec:
  selector:
    app:  shoppingclient
  type:  NodePort
  ports:
  - protocol: TCP
    port: 8001
    targetPort: 80
    nodePort: 30000